name: scroll_time_picker
description: A new flutter plugin project.
version: 0.0.1
homepage: https://github.com/mincheol-shin/scroll_time_picker

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
